In [1]:
%matplotlib inline
import sklearn
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
import numpy as np
from sklearn.model_selection import KFold
from mylibs import transform
from sklearn import neighbors
from sklearn.naive_bayes import GaussianNB
from sklearn import svm

In [2]:
X,y = sklearn.datasets.load_boston(return_X_y=True)
X = transform.standardize(X)
kfold = KFold(n_splits=5)

In [3]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)


for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    modelo = linear_model.LinearRegression()
    modelo.fit(Xtrain,y_train)
    y_pred = modelo.predict(Xtest)
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)


print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))

[3.53279637 5.10844425 5.75499399 8.99072043 5.79520109]
[2.62469524 3.91244817 4.38945068 5.57366377 4.78261237]
5.795201088167998
4.782612366965594


In [4]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
gradient = linear_model.SGDRegressor()

for idx_train, idx_test in kfold.split(X):
    print("Aqui")
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    gradient.fit(Xtrain,y_train)
    y_pred = gradient.predict(Xtest)
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)


print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))


Aqui
Aqui
Aqui
Aqui
Aqui
[3.11311838 6.32280183 5.91300661 8.96338742 7.91668982]
[2.25375786 4.72564065 4.14837281 5.36214956 5.92537272]
7.916689824576685
5.925372721611


/home/darkbyte/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


#### KNN

In [5]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
knn = neighbors.KNeighborsRegressor()

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    knn.fit(Xtrain,y_train)
    y_pred = knn.predict(Xtest)
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)

print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))

[3.76753937 5.80193925 5.61749953 6.80418508 4.7085286 ]
[2.93764706 3.75623762 4.17465347 4.06851485 3.57425743]
4.708528600758247
3.574257425742574


In [6]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
naivebayes = GaussianNB()

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    naivebayes.fit(Xtrain.astype(float),y_train.astype(int))
    y_pred = naivebayes.predict(Xtest.astype(float))
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)

print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))

[ 5.23636418  6.1821205   9.96697517 10.4351083   6.19088279]
[4.07156863 4.63564356 6.88118812 7.10891089 4.44455446]
6.190882788663528
4.444554455445545


In [7]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
svm = svm.SVR()

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    svm.fit(Xtrain.astype(float),y_train.astype(int))
    y_pred = svm.predict(Xtest.astype(float))
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)

print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))

[2.89634311 6.85284779 8.85535558 7.57552989 5.70077567]
[2.09855906 4.32743364 6.14518067 4.40433799 4.31927614]
5.7007756662171065
4.319276138322922


### Classificação

In [8]:
X,y = sklearn.datasets.load_breast_cancer(return_X_y=True)
X = transform.normalize(X)
kfold = KFold(n_splits=5)

#### Logistic regression

In [9]:
model = linear_model.LogisticRegression()
recalls = np.empty((1,0),dtype = float)
acuracias = np.empty((1,0),dtype = float)
precisions = np.empty((1,0),dtype = float)
f1s = np.empty((1,0),dtype = float)
aucs = np.empty((1,0),dtype = float)

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    model.fit(Xtrain,y_train)
    y_pred = model.predict(Xtest)
    acuracia = metrics.accuracy_score(y_test,y_pred)
    precision = metrics.precision_score(y_test,y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    recalls = np.append(recalls,recall)
    acuracias = np.append(acuracias,acuracia)
    precisions = np.append(precisions,precision)
    f1s = np.append(f1s,f1)
    auc = metrics.roc_auc_score(y_test,y_pred)
    aucs = np.append(aucs,auc)

print(np.mean(recalls))
print(np.mean(acuracias))
print(np.mean(precisions))
print(np.mean(f1s))
print(np.mean(aucs))



0.9910003821618603
0.9543704393727681
0.9291092039843047
0.9578514504482583
0.951019502253675


### KNN

In [10]:
model = neighbors.KNeighborsClassifier()

recalls = np.empty((1,0),dtype = float)
acuracias = np.empty((1,0),dtype = float)
precisions = np.empty((1,0),dtype = float)
f1s = np.empty((1,0),dtype = float)
aucs = np.empty((1,0),dtype = float)

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    model.fit(Xtrain,y_train)
    y_pred = model.predict(Xtest)
    acuracia = metrics.accuracy_score(y_test,y_pred)
    precision = metrics.precision_score(y_test,y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    #Preenchimento de vetores
    recalls = np.append(recalls,recall)
    acuracias = np.append(acuracias,acuracia)
    precisions = np.append(precisions,precision)
    f1s = np.append(f1s,f1)
    auc = metrics.roc_auc_score(y_test,y_pred)
    aucs = np.append(aucs,auc)

print(np.mean(recalls))
print(np.mean(acuracias))
print(np.mean(precisions))
print(np.mean(f1s))
print(np.mean(aucs))


0.9844077961019491
0.9631113181183046
0.9488713787902429
0.9658345095536731
0.9588907797001859


### Naive bayes

In [11]:
model = GaussianNB()
recalls = np.empty((1,0),dtype = float)
acuracias = np.empty((1,0),dtype = float)
precisions = np.empty((1,0),dtype = float)
f1s = np.empty((1,0),dtype = float)
aucs = np.empty((1,0),dtype = float)

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    model.fit(Xtrain,y_train)
    y_pred = model.predict(Xtest)
    acuracia = metrics.accuracy_score(y_test,y_pred)
    precision = metrics.precision_score(y_test,y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    #Preenchimento de vetores
    recalls = np.append(recalls,recall)
    acuracias = np.append(acuracias,acuracia)
    precisions = np.append(precisions,precision)
    f1s = np.append(f1s,f1)
    auc = metrics.roc_auc_score(y_test,y_pred)
    aucs = np.append(aucs,auc)

print(np.mean(recalls))
print(np.mean(acuracias))
print(np.mean(precisions))
print(np.mean(f1s))
print(np.mean(aucs))


0.9499018461907605
0.9296848315478963
0.9265098375113417
0.9372205053092115
0.9259112833668098


### SVM

In [13]:
model = sklearn.svm.SVC()
recalls = np.empty((1,0),dtype = float)
acuracias = np.empty((1,0),dtype = float)
precisions = np.empty((1,0),dtype = float)
f1s = np.empty((1,0),dtype = float)
aucs = np.empty((1,0),dtype = float)

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    model.fit(Xtrain,y_train)
    y_pred = model.predict(Xtest)
    acuracia = metrics.accuracy_score(y_test,y_pred)
    precision = metrics.precision_score(y_test,y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    #Preenchimento de vetores
    
    recalls = np.append(recalls,recall)
    acuracias = np.append(acuracias,acuracia)
    precisions = np.append(precisions,precision)
    f1s = np.append(f1s,f1)
    auc = metrics.roc_auc_score(y_test,y_pred)
    aucs = np.append(aucs,auc)

print(np.mean(recalls))
print(np.mean(acuracias))
print(np.mean(precisions))
print(np.mean(f1s))
print(np.mean(aucs))


0.9499018461907605
0.9296848315478963
0.9265098375113417
0.9372205053092115
0.9259112833668098
