In [1]:
%matplotlib inline
from matplotlib import pyplot as plt

import sklearn
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
import numpy as np
from sklearn.model_selection import KFold
from mylibs import transform
from sklearn import neighbors
from sklearn.naive_bayes import GaussianNB
from sklearn import svm

In [2]:
X,y = sklearn.datasets.load_boston(return_X_y=True)
X = transform.standardize(X)
kfold = KFold(n_splits=5)

In [3]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)


for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    modelo = linear_model.LinearRegression()
    modelo.fit(Xtrain,y_train)
    y_pred = modelo.predict(Xtest)
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)


print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))

[3.53279637 5.10844425 5.75499399 8.99072043 5.79520109]
[2.62469524 3.91244817 4.38945068 5.57366377 4.78261237]
5.795201088167998
4.782612366965594


In [4]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
gradient = linear_model.SGDRegressor()

for idx_train, idx_test in kfold.split(X):
    print("Aqui")
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    gradient.fit(Xtrain,y_train)
    y_pred = gradient.predict(Xtest)
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)


print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))


Aqui
Aqui
Aqui
Aqui
Aqui
[3.12713369 6.25650956 5.92060226 8.68529473 7.61024062]
[2.25236973 4.72268829 4.16940382 5.17932702 5.73482759]
7.610240616998319
5.734827593666171


/home/null/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


#### KNN

In [5]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
knn = neighbors.KNeighborsRegressor()

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    knn.fit(Xtrain,y_train)
    y_pred = knn.predict(Xtest)
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)

print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))

[3.76753937 5.80193925 5.61749953 6.80418508 4.7085286 ]
[2.93764706 3.75623762 4.17465347 4.06851485 3.57425743]
4.708528600758247
3.574257425742574


In [6]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
naivebayes = GaussianNB()

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    naivebayes.fit(Xtrain.astype(float),y_train.astype(int))
    y_pred = naivebayes.predict(Xtest.astype(float))
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)

print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))

[ 5.23636418  6.1821205   9.96697517 10.4351083   6.19088279]
[4.07156863 4.63564356 6.88118812 7.10891089 4.44455446]
6.190882788663528
4.444554455445545


In [7]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
svm = svm.SVR()

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    svm.fit(Xtrain.astype(float),y_train.astype(int))
    y_pred = svm.predict(Xtest.astype(float))
    erro_mse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)

print(erros_mse)
print(erros_mae)

print(np.mean(erro_mse))
print(np.mean(erro_mae))

[2.89634311 6.85284779 8.85535558 7.57552989 5.70077567]
[2.09855906 4.32743364 6.14518067 4.40433799 4.31927614]
5.7007756662171065
4.319276138322922


#### Melhor modelo (KNN)

In [8]:
knn = neighbors.KNeighborsRegressor()
knn.fit(X,y)
y_pred = knn.predict(X)

print(np.sqrt(metrics.mean_squared_error(y,y_pred)))

3.3672833022994464


### Classificação

In [9]:
X,y = sklearn.datasets.load_breast_cancer(return_X_y=True)
X = transform.normalize(X)
kfold = sklearn.model_selection.StratifiedKFold

#### Logistic regression

In [10]:
model = linear_model.LogisticRegression()
recalls = np.empty((1,0),dtype = float)
acuracias = np.empty((1,0),dtype = float)
precisions = np.empty((1,0),dtype = float)
f1s = np.empty((1,0),dtype = float)
aucs = np.empty((1,0),dtype = float)

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    model.fit(Xtrain,y_train)
    y_pred = model.predict(Xtest)
    acuracia = metrics.accuracy_score(y_test,y_pred)
    precision = metrics.precision_score(y_test,y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    recalls = np.append(recalls,recall)
    acuracias = np.append(acuracias,acuracia)
    precisions = np.append(precisions,precision)
    f1s = np.append(f1s,f1)
    auc = metrics.roc_auc_score(y_test,y_pred)
    aucs = np.append(aucs,auc)
    
    
    fpr, tpr, thr = metrics.roc_curve(y_test, y_pred)
    roc = metrics.auc(fpr, tpr)
    plt.figure();
    plt.plot(fpr, tpr, color='darkorange',
    lw=2, label='ROC curve (area = %0.2f)' % roc)
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve')
    plt.legend(loc="lower right")
    plt.show()
    print(metrics.confusion_matrix(y_test, y_pred, labels=np.unique(y_test)))

print(np.mean(recalls))
print(np.mean(acuracias))
print(np.mean(precisions))
print(np.mean(f1s))
print(np.mean(aucs))



TypeError: split() missing 2 required positional arguments: 'X' and 'y'

### KNN

In [ ]:
model = neighbors.KNeighborsClassifier()

recalls = np.empty((1,0),dtype = float)
acuracias = np.empty((1,0),dtype = float)
precisions = np.empty((1,0),dtype = float)
f1s = np.empty((1,0),dtype = float)
aucs = np.empty((1,0),dtype = float)

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    model.fit(Xtrain,y_train)
    y_pred = model.predict(Xtest)
    acuracia = metrics.accuracy_score(y_test,y_pred)
    precision = metrics.precision_score(y_test,y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    #Preenchimento de vetores
    recalls = np.append(recalls,recall)
    acuracias = np.append(acuracias,acuracia)
    precisions = np.append(precisions,precision)
    f1s = np.append(f1s,f1)
    auc = metrics.roc_auc_score(y_test,y_pred)
    aucs = np.append(aucs,auc)
    
    fpr, tpr, thr = metrics.roc_curve(y_test, y_pred)
    roc = metrics.auc(fpr, tpr)
    plt.figure();
    plt.plot(fpr, tpr, color='darkorange',
    lw=2, label='ROC curve (area = %0.2f)' % roc)
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve')
    plt.legend(loc="lower right")
    plt.show()
    print(metrics.confusion_matrix(y_test, y_pred, labels=np.unique(y_test)))
    
print(np.mean(recalls))
print(np.mean(acuracias))
print(np.mean(precisions))
print(np.mean(f1s))
print(np.mean(aucs))


### Naive bayes

In [ ]:
model = GaussianNB()
recalls = np.empty((1,0),dtype = float)
acuracias = np.empty((1,0),dtype = float)
precisions = np.empty((1,0),dtype = float)
f1s = np.empty((1,0),dtype = float)
aucs = np.empty((1,0),dtype = float)

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    model.fit(Xtrain,y_train)
    y_pred = model.predict(Xtest)
    acuracia = metrics.accuracy_score(y_test,y_pred)
    precision = metrics.precision_score(y_test,y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    #Preenchimento de vetores
    recalls = np.append(recalls,recall)
    acuracias = np.append(acuracias,acuracia)
    precisions = np.append(precisions,precision)
    f1s = np.append(f1s,f1)
    auc = metrics.roc_auc_score(y_test,y_pred)
    aucs = np.append(aucs,auc)

    fpr, tpr, thr = metrics.roc_curve(y_test, y_pred)
    roc = metrics.auc(fpr, tpr)
    plt.figure();
    plt.plot(fpr, tpr, color='darkorange',
    lw=2, label='ROC curve (area = %0.2f)' % roc)
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve')
    plt.legend(loc="lower right")
    plt.show()
    print(metrics.confusion_matrix(y_test, y_pred, labels=np.unique(y_test)))

print(np.mean(recalls))
print(np.mean(acuracias))
print(np.mean(precisions))
print(np.mean(f1s))
print(np.mean(aucs))


### SVM

In [ ]:
model = sklearn.svm.SVC()
recalls = np.empty((1,0),dtype = float)
acuracias = np.empty((1,0),dtype = float)
precisions = np.empty((1,0),dtype = float)
f1s = np.empty((1,0),dtype = float)
aucs = np.empty((1,0),dtype = float)

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    model.fit(Xtrain,y_train)
    y_pred = model.predict(Xtest)
    acuracia = metrics.accuracy_score(y_test,y_pred)
    precision = metrics.precision_score(y_test,y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
   
    fpr, tpr, thr = metrics.roc_curve(y_test, y_pred)
    roc = metrics.auc(fpr, tpr)
    plt.figure();
    plt.plot(fpr, tpr, color='darkorange',
    lw=2, label='ROC curve (area = %0.2f)' % roc)
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve')
    plt.legend(loc="lower right")
    plt.show()
    
    #Preenchimento de vetores
    recalls = np.append(recalls,recall)
    acuracias = np.append(acuracias,acuracia)
    precisions = np.append(precisions,precision)
    f1s = np.append(f1s,f1)
    auc = metrics.roc_auc_score(y_test,y_pred)
    aucs = np.append(aucs,auc)
    
    print(metrics.confusion_matrix(y_test, y_pred, labels=np.unique(y_test)))
    
print(np.mean(recalls))
print(np.mean(acuracias))
print(np.mean(precisions))
print(np.mean(f1s))
print(np.mean(aucs))

##### Melhor modelo

In [ ]:
model = neighbors.KNeighborsClassifier()
model.fit(X,y)
y_pred = model.predict(X)
print(metrics.accuracy_score(y,y_pred))