In [38]:
%matplotlib inline
import sklearn
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
import numpy as np
from sklearn.model_selection import KFold
from mylibs import transform
from sklearn import neighbors
from sklearn.naive_bayes import GaussianNB

In [11]:
X,y = sklearn.datasets.load_boston(return_X_y=True)
X = transform.standardize(X)
kfold = KFold(n_splits=5)

In [50]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)


for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    modelo = linear_model.LinearRegression()
    modelo.fit(Xtrain,y_train)
    y_pred = modelo.predict(Xtest)
    erro_mse = metrics.mean_squared_error(y_test,y_pred)
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)


print(erros_mse)
print(erros_mae)

[12.48065021 26.09620267 33.11995587 80.83305378 33.58435565]
[2.62469524 3.91244817 4.38945068 5.57366377 4.78261237]


In [51]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
gradient = linear_model.SGDRegressor()

for idx_train, idx_test in kfold.split(X):
    print("Aqui")
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    gradient.fit(Xtrain,y_train)
    y_pred = gradient.predict(Xtest)
    erro_mse = metrics.mean_squared_error(y_test,y_pred)
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)


print(erros_mse)
print(erros_mae)


Aqui
Aqui
Aqui
Aqui
Aqui
[10.04324725 39.77094341 36.26996833 78.71669066 57.58537649]
[2.28156345 4.7426195  4.22107209 5.28643311 5.72388061]


/home/null/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


#### KNN

In [52]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
knn = neighbors.KNeighborsRegressor()

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    knn.fit(Xtrain,y_train)
    y_pred = knn.predict(Xtest)
    erro_mse = metrics.mean_squared_error(y_test,y_pred)
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)

print(erros_mse)
print(erros_mae)

[14.19435294 33.66249901 31.55630099 46.29693465 22.17024158]
[2.93764706 3.75623762 4.17465347 4.06851485 3.57425743]


In [53]:
erros_mse = np.empty((1,0),dtype = float)
erros_mae = np.empty((1,0),dtype = float)
naivebayes = GaussianNB()

for idx_train, idx_test in kfold.split(X):
    Xtrain = X[idx_train]
    Xtest = X[idx_test]
    y_train = y[idx_train]
    y_test = y[idx_test]
    naivebayes.fit(Xtrain.astype(float),y_train.astype(int))
    y_pred = naivebayes.predict(Xtest.astype(float))
    erro_mse = metrics.mean_squared_error(y_test,y_pred)
    erro_mae = metrics.mean_absolute_error(y_test,y_pred)
    erros_mse = np.append(erros_mse,erro_mse)
    erros_mae = np.append(erros_mae,erro_mae)

print(erros_mse)
print(erros_mae)

[ 27.4195098   38.21861386  99.34059406 108.89148515  38.3270297 ]
[4.07156863 4.63564356 6.88118812 7.10891089 4.44455446]
